import { css } from '@emotion/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Posts from '@/components/Posts';
import Header from '@/components/Header';

const Home: NextPage = () => {
  // CSS

  const main = css`
    min-height: 100vh;
    padding: 4rem 0;
    flex: 1;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
  `;
  const footer = css`
    display: flex;
    flex: 1;
    padding: 2rem 0;
    border-top: 1px solid #eaeaea;
    justify-content: center;
    align-items: center;
    a {
      display: flex;
      justify-content: center;
      align-items: center;
      flex-grow: 1;
    }
    @media (prefers-color-scheme: dark) {
      border-color: #222;
    }
  `;
  const title = css`
    margin: 0;
    line-height: 1.15;
    font-size: 4rem;
    text-align: center;
    a {
      color: #0070f3;
      text-decoration: none;
      &:hover,
      &:focus,
      &:active {
        text-decoration: underline;
      }
    }
  `;
  const description = css`
    text-align: center;
    margin: 4rem 0;
    line-height: 1.5;
    font-size: 1.5rem;
  `;
  const logo = css`
    height: 1em;
    margin-left: 0.5rem;
    @media (prefers-color-scheme: dark) {
      img {
        filter: invert(1);
      }
    }
  `;

  // TSX
  return (
    <div>
      <Head>
        <title>4畳半からお届け</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* TitleHeader */}
      <Header />
      {/* SearchBar */}
      {/* Posts */}
      <Posts />
    </div>
  );
};

export default Home;
