import { css } from '@emotion/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import * as styles from '../styles/index.styles';

const Home: NextPage = () => {
  // CSS
  const container = css`
    padding: 0 2rem;
  `;
  const main = css`
    min-height: 100vh;
    padding: 4rem 0;
    flex: 1;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
  `;
  const footer = css`
    display: flex;
    flex: 1;
    padding: 2rem 0;
    border-top: 1px solid #eaeaea;
    justify-content: center;
    align-items: center;
    a {
      display: flex;
      justify-content: center;
      align-items: center;
      flex-grow: 1;
    }
    @media (prefers-color-scheme: dark) {
      border-color: #222;
    }
  `;
  const title = css`
    margin: 0;
    line-height: 1.15;
    font-size: 4rem;
    text-align: center;
    a {
      color: #0070f3;
      text-decoration: none;
      &:hover,
      &:focus,
      &:active {
        text-decoration: underline;
      }
    }
  `;
  const description = css`
    text-align: center;
    margin: 4rem 0;
    line-height: 1.5;
    font-size: 1.5rem;
  `;
  const logo = css`
    height: 1em;
    margin-left: 0.5rem;
    @media (prefers-color-scheme: dark) {
      img {
        filter: invert(1);
      }
    }
  `;

  return (
    <div css={container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main css={main}>
        <h1 css={title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <p css={description}>
          Get started by editing <code css={styles.code}>pages/index.tsx</code>
        </p>

        <div css={styles.grid}>
          <a href='https://nextjs.org/docs' css={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href='https://nextjs.org/learn' css={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href='https://github.com/vercel/next.js/tree/canary/examples' css={styles.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            css={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
          </a>
        </div>
      </main>

      <footer css={footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span css={logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
